### ISSUE TITLE
No permission for GSAM Self Service Portal

### ISSUE THREAD

**Issue by airmelt-ms** [VSChina/onboarding-site#6]
I can't enter the link [GSAM Self Service Portal](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmicrosoft.sharepoint.com%2Fsites%2Fsecurity%2FServices%2FGSAM%2FPages%2FGSAM%2520Self%2520Service%2520Portal.aspx&data=04%7C01%7CHongkun.Chen%40microsoft.com%7Cdd1a9b0e35714e141e9b08d972916db4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637666791202883832%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KcMfKQG3DJauCDofmi4UV%2B7zeV2LXABfcykxIArTtOw%3D&reserved=0) in Useful Information/Access & Permission/Badge & Office Access.
Is [aka.ms/gsamssp ](aka.ms/gsamssp) the correct link?
Look forward to your apply, thanks!

**Comment by yungezz** [comment]
thanks for reporting the issue, would you like to contribute a PR? :)

**Comment by airmelt-ms** [comment]
OK, I will try.
